spring:
  application:
    name: config
  rabbitmq:
    host: 192.168.15.128
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      bindings:
       input :
        group : group1
        content-type : application/json
server:
  port: 8081